### ISSUE TITLE
Not able to execute cells given in notebooks

### ISSUE THREAD

**Issue by GhumanNavneet** [Microsoft/MCW-Cognitive-services-and-deep-learning#15]
Not able to execute the cell in Summarization notebook for exercise 2 ->task 2. Execution getting cancelled again and again for all notebooks.

**Comment by joelhulen** [comment]
Did you install the libraries in the cluster in the order shown, making sure each library was finished installing before installing the next?

If so, did your cluster restart away any point, perhaps due to inactivity?

The order in which these libraries are loaded is critical due to differences in dependency versions.

If the cluster restarts then the order in which the libraries are loaded is not guaranteed and you have to remove them and reinstall them one by one. This is a known issue with no other known workaround at this time.

**Comment by GhumanNavneet** [comment]
Yes, I have installed the library in the cluster in the order shown. I did not restart the cluster at any point while doing the lab.

**Comment by joelhulen** [comment]
I will try and reproduce the issue. In the meantime can you please delete and reinstall the libraries on the cluster in the prescribed order and try again?

**Comment by joelhulen** [comment]
@GhumanNavneet I've changed up the process to install libraries on the cluster. Can you please follow the updated instructions and let me know if it works out for you?
