### ISSUE TITLE
June 2019 - Content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Cognitive-services-and-deep-learning#21]
@ZoinerTejada @timahenning 
Hello,
This workshop is scheduled for a June 2019 update.  Please review the workshop and provide your update suggestions to be sent for SME review.
Thanks, Dawnmarie

**Comment by ZoinerTejada** [comment]
Here are the changes we suggest:

1. Convert the Hands-on lab to use Azure Notebooks running on DLVM
2. Use Keras instead of tflearn to build the claims classifier model
3. Convert Keras model to ONNX for inference
4. Highlight performance and portability of ONNX vs Keras on inference
5. Deploy ONNX model for use in scoring web service

As always, happy to receive input!

**Comment by swan-am-i** [comment]
Input from Rodrigo Souza:

This is a great work, my suggestions are simple:

1)	Content Moderator API has a good fit within the proposed scenario.
2)	The target audience is AI Developer and Data Scientist. But our new certifications use AI Engineer, not developer. I think we should use the  “same language”.
3)	Transform the target audience in links to the certifications or its learning paths.
4)	All readme.md files could have links for the next steps. People get confused: where I go now?
5)	No readme.md files inside the 2 folders of the repo. This readme.mds should have the required steps in order, with links.
6)	The solution “simple user interface” is one of the Databricks notebooks? I didn’t have time to do the lab yet, but it was not clear.
7)	Provide the estimated costs of the solution, per day and per month.

**Comment by swan-am-i** [comment]
Input from Julie Rachel:

Agreed, great work!  Due to time, I was only able to get through 04 and did not get to test 05 Cognitive Services.  Here are my thoughts.

+1 on the following items from Rodrigo; these are important.
2) The target audience is AI Developer and Data Scientist. But our new certifications use AI Engineer, not developer. I think we should use the  “same language”
3) Transform the target audience in links to the certifications or its learning paths.
4) All readme.md files could have links for the next steps. People get confused: where I go now?


Additional thoughts
1.	Add Azure Function to ‘Additional references’ in the Whiteboard design session ‘WDS student guide - Cognitive services and deep learning.md.’  I remember in my first couple of workshops not being familiar with Azure Function and it just being assumed that I did made figuring out the details during the workshop a little more difficult.
2.	Does the workshop assume there is knowledge of the different Azure services and related products that make up the architecture?  I am assuming it does because the ‘WDS trainer presentation - Cognitive Services and deep learning.pptx ‘ document doesn’t have any introduction to the Azure services.  It might be helpful to call that out in the documentation and provide a learning path to take before the workshop.   Perhaps in the Before the HOL documentation.

Within the notebook workshop steps feedback:

Exercise 1: Setup Azure Databricks Workspace
Task 3: Provision a cluster
1.	Within the Workspace, from the menu on the left, select Clusters.
2.	Select + Create Cluster.
3.	On the New Cluster page, provide the following:
a. Cluster Name: ailab
b. Cluster Mode: Standard
c. Databricks Runtime Version: 5.3 (includes Apache Spark 2.4.0, Scala 2.11)
d. Python Version: 3
e. Driver Type: Same as worker
f. Worker Type: Standard_F4s
g. Enable autoscaling: Unchecked
h: Workers: 2
e. and f. and g. are not aligned to the UI order.  I would put in the following order to make it easy to follow
e. Enable autoscaling: Unchecked
f. Worker Type: Standard_F4s
g. Driver Type: Same as worker


Exercise 2: Create and Deploy an Unsupervised Model 
Task 1: Install libraries
The notebook you will run depends on certain Python libraries like nltk and gensim that will need to be installed in your cluster. The following steps walk you through adding these dependencies.
1.	Within the Workspace, select the Workspace item in the menu and navigate to the folder where you uploaded the Databricks Archive (which should be [your-name/AI-lab]), and select the notebook called init. This will open the notebook so you can read and execute the code it contains.

Consider labeling init as 00 init so it shows up first in the list 

 

Create an Azure ML Workspace
Run the following cell and follow the instructions printed in the output. 
You will see instructions that read:
Performing interactive authentication. Please follow the instructions on the terminal.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code SOMECODE to authenticate.

Instead of SOMECODE – I would recommend you put CODEPROVIDED to avoid any confusion of someone putting in SOMECODE


03 Claims Classification

I assume you are aware but just in case, there are several times a warning regarding the version pops up since something is deprecated and will be removed in future version 
WARNING:tensorflow:From /databricks/python/lib/python3.5/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.


04 Deploy Classified Web Service
Cmd 10 
import os
##NOTE: service deployment always gets the model from the current working dir. 
tempFolderUUID = #"<your_temp_folder_uuid>" # UUID from previous notebook
tempFolderName = 'output/{0}'.format(tempFolderUUID)

model_name = "claim_classifier.tfl"
relative_model_path_local = tempFolderName
print("Using relative path to model output folder: ", relative_model_path_local)

uuid is found in cmd 5 in the Prepare Modules section of 03 Claims Classification…this might be a better comment that “#UUID from previous notebook”

**Comment by swan-am-i** [comment]
Lets include more LearnAI content

**Comment by DawnmarieDesJardins** [comment]
@ZoinerTejada @timahenning 
Hi Zoiner,
Please see feedback above.  Let us know if you have any questions to move forward with the update.
Thanks, Dawnmarie

**Comment by wmpauli** [comment]
This is great. I really like the integration of prebuilt and custom AI parts. The one thing one could consider for the hands-on exercises is to make the titles of the exercises more goal oriented, and the tasks more focused on the tools. E.g. exercise could be "Create summary of claim", and tasks could be "Build TF model" and "Deploy TF model" (i.e. tasks as is, but change title of exercises.

**Comment by dem108** [comment]
Code fix needed:
I was trying the lab and the [latest change](https://github.com/microsoft/MCW-Cognitive-services-and-deep-learning/issues/15#issuecomment-480067220) didn't work for me, because of a numpy version conflicts. The current `init` when you import [.dbc](https://github.com/microsoft/MCW-Cognitive-services-and-deep-learning/blob/master/Hands-on%20lab/media/notebooks/AI-Lab.dbc) tries to uninstall existing numpy and install a specific (maybe old) version, which breaks the cluster and render it useless to run any code with.

**Comment by dem108** [comment]
Great scenario and mix of services for such. I have some feedbacks to make this even more compelling:

1. Using Azure ML service Pipeline (with or without MLFlow) at `03. Claim Classification`, to showcase reusability, unattended runs, caching etc. Also show that these pipelines can be [published](https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-create-your-first-pipeline#publish-a-pipeline) and run outside of databricks. That means an integration with Azure Data Factory or even Azure DevOps.

1. Maybe consider migrating from tflearn to Keras, Tensorflow/PyTorch, and Horovod that is popular and ensures distributed training.

1. Showcase Databricks Secrets CLI to secure sensitive data. It's a premium feature and definitely useful for production scenarios. `05 Cognitive Services` has a direct need for this to keep the keys.

1. An addition of Azure DevOps will be really great. Databricks notebooks natively support [git integration](https://docs.azuredatabricks.net/user-guide/notebooks/github-version-control.html#link-a-notebook-to-github). We also have great [blog](https://databricks.com/blog/2017/10/30/continuous-integration-continuous-delivery-databricks.html) from Databricks, and a [talk at MLADS 2018](https://github.com/dem108/AMLWorkshop-IotEdge-DevOps/blob/master/doc/decks/219_Tutorial_MLADS_DevOps_for_AI_Praneet_Dmitry.pdf) on this.

**Comment by dem108** [comment]
Sorry I accidently closed this. Reopening this.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with June 2019 merge.
